#Example python program to remove unwanted sequences from a fasta file 
# First, using python regular expressions
# Second, using BioPython SeqIO

#With python regex:
#import the regular expression module
import re
#a pattern to match records whose names contain "uncultured" or "bacterium"
unwanted_sample_pattern = r""">\w+(uncultured|bacterium)[\w\n]+"""
#read the file in
fasta_data = open("example.fasta").read()
#replace each occurrence of the pattern found in fasta_data with the empty string
new_fasta_data = re.sub(unwanted_sample_pattern, "", fasta_data)
print new_fasta_data

#With BioPython
from Bio import SeqIO
handle = open("example.fasta", "rU")
records = list(SeqIO.parse(handle, "fasta"))
wanted_records = []
unwanted_sample_names = ["uncultured", "bacterium"]
for record in records:
    if not any(uwsn in record.name for uwsn in unwanted_sample_names):
        wanted_records.append(record)

output_handle = open("example_replaced.fasta", "w")
SeqIO.write(wanted_records, output_handle, "fasta")
output_handle.close()
    

#Example: the record for FN436082_uncultured_bacterium is removed, others are kept
"""
>FM994939_Clostridium_pasteurianum
GCAACCUGGCGGCGUGCUUAACACAUGCAAGUCGAGCGAGAAACCUUCGGGUUUCUAGCGGCGGACGGGUGAGUAACACG
UGGGUAACCUACCUCAAAGAGGGGAAUAGCCUCCCGAAAGGGAGAUUAAUACCGCAUAAUAUUACAGCUUCGCAUGAAGC
AGUAAUUAAAGGAGUAAUCCGCUUUGAGAUGGACCCGCGGCGCAUUAGCUAGUUGGAGAGGUAACGGCUCACCAAGGCGA
CGAUGCGUAGCCGACCUGAGAGGGUGAUCGGCCACAUUGGAACUGAGACACGGUCCAGACUCCUACGGGAGGCAGCAGUG
GGGAAUAUUGCACAAUGGGCGAAAGCCUGAUGCAGCAACGCCGCGUGAGUGAUGACGGUCUUCGGAUUGUAAAGCUCUGU
CUUUUGGGACGAUAAUGACGGUACCAAAGGAGGAAGCCACGGCUAACUACGUGCCAGCAGCCGCGGUAAUACGUAGGUGG
>FN436082_uncultured_bacterium
AGAGUUUGAUCCUGGCUCAGGACGAACGCUGGCGGCGUGCCUAACACAUGCAAGUCGAGCGAUGAAACCCUUCGGGGUGG
AUUAGCGGCGGACGGGUGAGUAACACGUGGGUAACCUGCCUCAAAGAGGGGAAUAGCCUUCCGAAAGGAAGAUUAAUACC
GCAUAAUAUGUUUUGGUCGCAUGACCUAGACAUCAAAGGAGUAAUCCGCUUUGAGAUGGACCCGCGGCGCAUUAGCUAGU
UGGUGAGGUAACGGCUCACCAAGGCGACGAUGCGUAGCCGACCUGAGAGGGUGAUCGGCCACAUUGGAACUGAGACACGG
UCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCGCAAUGGGGGAAACCCUGACGCAGCAACGCCGCGUGAAUGAU
>FM994939_Clostridium_pasteurianum
GCAACCUGGCGGCGUGCUUAACACAUGCAAGUCGAGCGAGAAACCUUCGGGUUUCUAGCGGCGGACGGGUGAGUAACACG
UGGGUAACCUACCUCAAAGAGGGGAAUAGCCUCCCGAAAGGGAGAUUAAUACCGCAUAAUAUUACAGCUUCGCAUGAAGC
AGUAAUUAAAGGAGUAAUCCGCUUUGAGAUGGACCCGCGGCGCAUUAGCUAGUUGGAGAGGUAACGGCUCACCAAGGCGA
CGAUGCGUAGCCGACCUGAGAGGGUGAUCGGCCACAUUGGAACUGAGACACGGUCCAGACUCCUACGGGAGGCAGCAGUG
"""